provider: openrouter
model: deepseek/deepseek-r1-0528:free
api_key: os.environ.get("API_KEY")
api_url: https://openrouter.ai/api/v1/chat/completions
max_tokens: 512
temperature: 0.0
timeout: 30
retry_attempts: 3
site_url: http://localhost:8000
site_name: AI Mood Food Recommender
